import Link from "next/link"
import { Button } from "@/components/ui/button"
import Navigation from "@/components/navigation"
import { CONFIG } from "@/config"

export const metadata = {
  title: `Terms of Service | ${CONFIG.site.name}`,
  description: "Terms of Service for Dailychatai AI Chat.",
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background text-foreground flex flex-col">
      <Navigation />
      <main className="flex-1 max-w-3xl mx-auto px-4 py-12 w-full">
        <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
        <p className="text-muted-foreground text-sm mb-8">Last updated: {new Date().toLocaleDateString("en-US")}</p>

        <div className="prose prose-neutral dark:prose-invert max-w-none space-y-6 text-muted-foreground text-sm">
          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">1. Acceptance of Terms</h2>
            <p>
              By accessing or using Dailychatai AI Chat (&quot;the Service&quot;), you agree to be bound by these
              Terms of Service. If you do not agree to these terms, please do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">2. Description of Service</h2>
            <p>
              Dailychatai AI Chat is an AI-powered chatbot that allows you to send messages and receive
              responses generated by third-party AI models (e.g., via OpenRouter). The Service may include
              optional features such as user accounts, conversation history, and subscription plans.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">3. Use of the Service</h2>
            <p>
              You agree to use the Service only for lawful purposes and in accordance with these Terms.
              You must not use the Service to transmit harmful, offensive, or illegal content, or to
              attempt to gain unauthorized access to any systems or data.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">4. AI-Generated Content</h2>
            <p>
              Responses from the chatbot are generated by AI and may be inaccurate or inappropriate. Do
              not rely on the Service for medical, legal, financial, or other professional advice. We do
              not guarantee the accuracy, completeness, or suitability of any AI-generated content.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">5. Accounts and Data</h2>
            <p>
              If you create an account, you are responsible for keeping your credentials secure and for
              all activity under your account. We may collect and process data as described in our{" "}
              <Link href="/privacy" className="text-primary underline hover:no-underline">
                Privacy Policy
              </Link>
              .
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">6. Limitation of Liability</h2>
            <p>
              The Service is provided &quot;as is&quot; without warranties of any kind. To the fullest extent
              permitted by law, we shall not be liable for any indirect, incidental, special, or
              consequential damages arising from your use of the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">7. Changes</h2>
            <p>
              We may update these Terms from time to time. Continued use of the Service after changes
              constitutes acceptance of the revised Terms. We encourage you to review this page
              periodically.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">8. Contact</h2>
            <p>
              For questions about these Terms, please visit our{" "}
              <Link href="/contact" className="text-primary underline hover:no-underline">
                Contact
              </Link>{" "}
              page.
            </p>
          </section>
        </div>

        <div className="mt-10">
          <Link href="/">
            <Button variant="outline">Back to home</Button>
          </Link>
        </div>
      </main>
    </div>
  )
}
